version: "3.7"
services:
 web:
  build: "./frontend"
  ports: 
   - "8080:80"
 influx-grafana:
  image: "philhawthorne/docker-influxdb-grafana:latest"
  ports:
  - "3003:3003"
  - "3004:8083"
  - "8086:8086"
  volumes:
   - "./influx:/var/lib/influxdb"
   - "./grafana:/var/lib/grafana"
   - "./backend/dashboards-scheme:/var/lib/grafana/dashboards"
   - "./backend/datasources:/etc/grafana/provisioning/datasources"
   - "./backend/dashboards:/etc/grafana/provisioning/dashboards"

