version: "3.7"
services:
 web:
  build: "../frontend/dev-version"
  ports: 
   - "8080:80"
  volumes:
   - "../frontend/html:/usr/share/nginx/html"
 influx-grafana:
  image: "philhawthorne/docker-influxdb-grafana:latest"
  ports:
  - "3003:3003"
  - "3004:8083"
  - "8086:8086"
  volumes:
   - "../docker-influx-volume:/var/lib/influxdb"
   - "../backend/scripts:/var/lib/influxdb/scripts"
   - "../docker-grafana-volume:/var/lib/grafana"
   - "../backend/dashboards-scheme:/var/lib/grafana/dashboards"
   - "../backend/datasources:/etc/grafana/provisioning/datasources"
   - "../backend/dashboards:/etc/grafana/provisioning/dashboards"

